version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dkuser
      POSTGRES_PASSWORD: dkpass
      POSTGRES_DB: dkkdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
volumes:
  db_data:
